apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: dhis2-postgis16-cluster
  namespace: dhis2
  labels:
    app: dhis2-postgis16-cluster
spec:
  imageName: ghcr.io/cloudnative-pg/postgis:16-3.4
  instances: 3
  startDelay: 900
  stopDelay: 900
  primaryUpdateStrategy: unsupervised

# PostGres Best Practices for the Logging 
  #  - https://www.enterprisedb.com/blog/how-get-best-out-postgresql-logs
  #  - https://medium.com/google-cloud/correlate-statement-logs-in-cloudsql-for-postgres-with-connection-sessions-5bae4ade38f5
  #  - PostgreSQL Official Documentation on pg_stat_statements: https://www.postgresql.org/docs/current/pgstatstatements.html
  #  - pgAudit GitHub Repository: https://github.com/pgaudit/pgaudit
  postgresql:
    parameters:
      log_min_messages: "warning" # From "error" to "warning" to reduce informational messages
      pg_stat_statements.track: top # From "all" to "top" to only track top-level statements
      auto_explain.log_min_duration: '30s' # From "10s" to "30s" to reduce slow query logs
      pgaudit.log: "none"
      log_connections: "off" # Reduced connection logs
      log_disconnections: "off" # Reduced disconnection logs
      log_hostname: "off" # Avoided logging hostnames
      log_temp_files: "1024" # Log temp files larger than 1MB
      log_lock_waits: "on" # Keep "on" if monitoring for lock waits
      log_checkpoints: "on" # Keep "on" for checkpointing information
      shared_buffers: 256MB
      pg_stat_statements.max: '10000'
      pgaudit.log_catalog: "off"
      pgaudit.log_parameter: "on"
      pgaudit.log_relation: "on"
    pg_hba:
      - host all all all md5


  bootstrap:
    initdb:
      database: dhis
      owner: dhis
      postInitApplicationSQL:
        - CREATE EXTENSION postgis;
        - CREATE EXTENSION postgis_topology;
        - CREATE EXTENSION fuzzystrmatch;
        - CREATE EXTENSION postgis_tiger_geocoder;

  storage:
    storageClass: standard
    size: 5Gi

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: false

  # serviceAccountTemplate:
  #   metadata:
  #     annotations:
  #       # k8s service account is created with the same as `metadata.name` above
  #       # ensure an appropriate storage role(s) and workload identity is assigned: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
  #       iam.gke.io/gcp-service-account: dhis2-postgis-backup@phx-01h28kjpmp42v8xh59v0qvfpxa.iam.gserviceaccount.com

  # # info: https://cloudnative-pg.io/documentation/1.21/appendixes/object_stores/#running-inside-google-kubernetes-engine
  # backup:
  #   barmanObjectStore:
  #     destinationPath: gs://dhis2-postgis-backup-phx-01h28kjpmp42v8xh59v0qvfpxa
  #     googleCredentials:
  #       gkeEnvironment: true
  #   retentionPolicy: "90d"

  inheritedMetadata:
    annotations:
      proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      sidecar.istio.io/proxyCPU: 50m
      sidecar.istio.io/proxyMemory: 52Mi

  resources:
    requests:
      cpu: 450m
      memory: 1926Mi