apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gw-certificate.yaml
- mesh-gateway.yaml
- ingress.yaml
- namespace.yaml

patches:
# Patch the Istio ingress service so that our IP is used.
- patch: |-
    - op: add
      path: /spec/loadBalancerIP
      value: 35.234.247.199
  target:
    kind: Service
    name: istio-ingressgateway
    namespace: istio-ingress
    version: v1